# Generated by Django 4.0.4 on 2022-05-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_desafio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='creacion',
            field=models.IntegerField(),
        ),
    ]
