# Generated by Django 4.0.4 on 2022-05-31 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_desafio', '0002_alter_auto_creacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trabajadores',
            new_name='Oficinas',
        ),
        migrations.RenameField(
            model_name='oficinas',
            old_name='cantidad_trabajadores',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='oficinas',
            old_name='trabajo',
            new_name='tipos',
        ),
    ]
